<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="7.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Delta.DocView.Shared\Delta.DocView.Shared.csproj" />
    <ProjectReference Include="..\Delta.DocView.Client\Delta.DocView.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schemas\step-library.v1.schema.json"
                      LogicalName="step-library.v1.schema.json" />
  </ItemGroup>
</Project>
